apiVersion: v1
kind: Pod
metadata:
  name: task-b
spec:
  containers:
  - name: busyhost
    image: busybox:latest
    command: ["/bin/sh", "-ec", "while :; do echo '.+B'; sleep 5 ; done"]
    resources:
      requests:
        memory: "2048Mi"
        cpu: "2"
      limits:
        memory: "2048Mi"
        cpu: "2"
  nodeSelector:
    "node-role.kubernetes.io/edge": ""