apiVersion: v1
kind: Pod
metadata:
  name: task-a
spec:
  containers:
  - name: busyhost
    image: busybox:latest
    command: ["/bin/sh", "-ec", "while :; do echo '.+A'; sleep 5 ; done"]
    resources:
      requests:
        memory: "1024Mi"
        cpu: "1"
      limits:
        memory: "1024Mi"
        cpu: "1"
  nodeSelector:
    "node-role.kubernetes.io/edge": ""